### ISSUE TITLE
Annotate Info about nullability

### ISSUE THREAD

**Issue by svenefftinge** [TypeFox/ls-api#1]
We should add nullable annotations.

**Comment by svenefftinge** [comment]
And check during de/serialization

**Comment by spoenemann** [comment]
From where should we take `@Nullable`? I found it in `com.google.code.findbugs:jsr305:3.0.1`

**Comment by svenefftinge** [comment]
jsr305 sounds good, is there no more official group providing it?

**Comment by spoenemann** [comment]
It is [used by Guice and Guava](https://github.com/google/guice/wiki/UseNullable), so it seems a good choice. See also http://stackoverflow.com/questions/2289694/what-is-the-status-of-jsr-305
