### ISSUE TITLE
Produce p2 repo

### ISSUE THREAD

**Issue by mickaelistria** [TypeFox/ls-api#11]
In order to more easily consume this library in the Eclipse world, it would be useful to produce a p2 repository for it.

**Comment by spoenemann** [comment]
Since the next version of [Xtext](http://xtext.org) will depend on ls-api, it will provide it either as part of its own update site or as part of [Orbit](https://www.eclipse.org/orbit/).

**Comment by mickaelistria** [comment]
Good news, thanks.

**Comment by mickaelistria** [comment]
By the way, for XText, do you already have a working client consuming the language service to hook some behavior (validation, completion...) into the Eclipse IDE ?

**Comment by svenefftinge** [comment]
Yes, we could provide an example language that does these features.

**Comment by mickaelistria** [comment]
Thanks, that would be useful.

**Comment by svenefftinge** [comment]
See https://github.com/TypeFox/languageserver-example

**Comment by mickaelistria** [comment]
Is there already a snapshot of a p2 repo for XText I can use to get p2-friendly artifacts for ls-api?

**Comment by svenefftinge** [comment]
@meysholdt could you help Mickael to get the bits into a target platform? I think you did that in the Xtext build.

**Comment by meysholdt** [comment]
The p2 repository for all Xtext artifacts is here:
http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/master/lastSuccessfulBuild/artifact/build/p2-repository/

However, lsapi is not included, because no Eclipse Feature includes it.

Do we want 
a) the lsapi project to have its own p2-repository site? 
b) Include lsapi into xtext-eclipse's p2-repository?

I think I'd vote for (a) as it's technologically independent of Xtext.

Having said that, the lsapi artifacts are already available via maven repository:
http://services.typefox.io/open-source/jenkins/job/lsapi/lastSuccessfulBuild/artifact/build/maven-repository/
and can be consumed by a maven tycho build, when setting <pomDependencies>consider</pomDependencies> in the target platform tycho plugin.

**Comment by mickaelistria** [comment]
Eclipse PDE doesn't understand pomDependencies=consider nor doesn't understand much Maven artifacts as OSGi bundle. So I cannot easily resolve this dependency in the IDE although it'd be doable with Maven. Inside the IDE, and inside shareable .target files, only p2 repo are supported.

About whether having it in XText repo or outside, I also believe a separate repo would be better. However, it's not a strong need at the moment, so if having it in XText snapshots is simpler for you, that would work for me.

**Comment by meysholdt** [comment]
about PDE: true.

**Comment by meysholdt** [comment]
I spoke with @svenefftinge, we're both in favor of having a dedicated p2-repo for lsapi. 
So I propose to create a minimal maven-tycho build that
- consumes the artifacts that we already produce with our gradle build via pomDependencies=consider
- creates an Eclipse Feature that includes lsapi and upstream dependencies.
- publishes the Eclipse Feature into a p2-repo

**Comment by meysholdt** [comment]
I added the needed maven-tycho code in 10be7e63060e62987ed6973f923877f382e11cb5

TODO: run maven-tycho from either gradle or jenkins

**Comment by meysholdt** [comment]
fixed, we have a p2-repo now

http://services.typefox.io/open-source/jenkins/job/lsapi/lastSuccessfulBuild/artifact/build/p2-repository/

**Comment by mickaelistria** [comment]
Thanks a lot. However, p2 installation seems to be inconsistent because of issue #19 . Bundles get installed, but we get ClassNotFound at runtime.

**Comment by mickaelistria** [comment]
Thanks a lot. However, p2 installation seems to be inconsistent because of issue #19 . Bundles get installed, but we get ClassNotFound at runtime.

**Comment by mickaelistria** [comment]
http://services.typefox.io/open-source/jenkins/job/lsapi/lastSuccessfulBuild/artifact/build/p2-repository/ gives a Proxy error

```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /open-source/jenkins/job/xtext-eclipse/job/master/lastSuccessfulBuild/artifact/build/p2-repository/.

Reason: DNS lookup failure for: oss-jenkins
```

Is there anything I should fix on my side?

**Comment by mickaelistria** [comment]
The repo seems back to work now.

**Comment by bruno-medeiros** [comment]
So, I tried to add http://services.typefox.io/open-source/jenkins//job/lsapi/lastSuccessfulBuild/artifact/build/p2-repository/ to my target platform (and the ls-api bundles in it), but resolving the platform fails because com.google.gson [2.5.0, 3.0.0) is required.
The latest version of the Eclipse Orbit repository ( http://download.eclipse.org/tools/orbit/downloads/drops/R20160520211859/ ) only has GSON up to version 2.2.4. Is there some other p2 repository I can get that version of GSON, and other ls-api dependencies?

**Comment by mickaelistria** [comment]
@bruno-medeiros For https://github.com/eclipselabs/eclipse-language-service/blob/master/org.eclipse.languageserver/pom.xml , I had to add pom dependencies to resolve gson 2.5. In the TP I use in the IDE, I simply added the jar by referencing it's location in my M2_REPO.
If you take https://github.com/eclipselabs/eclipse-language-service/blob/master/ and build it locally, the output p2 repo contains a p2-ified version of gson.

**Comment by bruno-medeiros** [comment]
> If you take https://github.com/eclipselabs/eclipse-language-service/blob/master/ and build it locally, the output p2 repo contains a p2-ified version of gson.

I tried just that (`mvn clean package`), but it doesn't create any gson bundle, only the ones listed in `eclipse-language-service\repository\category.xml` I had gson to the list there for it to be created.

**Comment by mickaelistria** [comment]
@bruno-medeiros I fixed that so that the bundle is now published. BTW, feel free to contribute to the eclipse-language-service repository, that'd be totally welcome! I already have C# completion and diagnostics reported into Eclipse IDE there.

**Comment by bruno-medeiros** [comment]
Well, a problem with http://services.typefox.io/open-source/jenkins/job/xtext-eclipse/job/master/lastSuccessfulBuild/artifact/build/p2-repository/ is that those bundles do not have sources attached.

**Comment by bruno-medeiros** [comment]
Opened #26

**Comment by mickaelistria** [comment]
@bruno-medeiros I fixed that so that the bundle is now published. BTW, feel free to contribute to the eclipse-language-service repository, that'd be totally welcome! I already have C# completion and diagnostics reported into Eclipse IDE there.
