### ISSUE TITLE
WorkspaceEdit: should store TextEdit[] instead of TextEdit in changes

### ISSUE THREAD

**Issue by joshtynjala** [TypeFox/ls-api#13]
Multiple changes can happen in the same file, but right now, it appears that only one is accepted.

See language-server-protocol documentation for [WorkspaceEdit](https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-1-x.md#workspaceedit).

Thanks!

**Comment by joshtynjala** [comment]
Thank you!

**Comment by spoenemann** [comment]
The change is available in version 0.3.0-SNAPSHOT
