### ISSUE TITLE
Show enums in Java-API

### ISSUE THREAD

**Issue by tomsontom** [TypeFox/ls-api#16]
Currently the API translates properties who are spec'ed as enums in Typescript through their integer value (which is the value used when serializing). 

It would be much easier to work with the API if the Java-API would represent them as Java-Enums when deserializing the JSON-Objects.

**Comment by svenefftinge** [comment]
The serialization still should use ints of course, and it would be good if it works with standard GSON. Seems like this pattern would do it : http://stackoverflow.com/a/27447586/1035471

**Comment by spoenemann** [comment]
That pattern requires `@SerializedName`, which has runtime retention and would give us a dependency to Gson in the lsapi base project. It would be better to avoid that dependency.

**Comment by tomsontom** [comment]
what about generating a 2nd set of methods who are doing the string/enum translation?

**Comment by tomsontom** [comment]
And I guess only the "impl" class need this annotation? Shouldn't those be hidden and one always uses the builder i requested in another issue?

**Comment by spoenemann** [comment]
Gson uses the fields of a class to serialize and parse it, not any methods. And even if we "hide" the impls, we would still require the dependency to Gson.

One solution could be to implement a generic Enum type adapter that uses the ordinal values of enum constants instead of their names. I'll give that a try.

**Comment by spoenemann** [comment]
The change is available in version 0.3.0-SNAPSHOT
