### ISSUE TITLE
Issues with source and javadoc attachement

### ISSUE THREAD

**Issue by bruno-medeiros** [TypeFox/ls-api#17]
I've been having some issues with source and javadoc attachment, which I'm not sure it's something I'm doing wrong, or a problem with ls-api itself.

So, I've built ls-api using gradlew (the tests fail BTW). I then added the `lsapi` and `lsapi.services` jars to my Eclipse project, added dependencies to my target plaform (like Google Guava and xtext.xbase.lib). I then tried to attach sources and javadoc to the the ls-api jars, and I also installed the Xtend IDE, however:
- Navigating (using F3 to open definition) into a ls-api element doesn't work most of the time. It finds and opens the source file, but doesn't find the correction location in the source. (also, the editor interprets the source as Java, not Xtend)
- Javadoc also seems to not work for most elements. For example, requesting the Javadoc pop-up for `getTextDocumentService()` of  `io.typefox.lsapi.services.LanguageServer` doesn't work, (even though Open Definition for that method reference does work). In the Javadoc setup in the Eclipse buildpath settings, I pressed the validate button to make sure the setup was correct, and it was validated correctly. I also opened the Javadoc jar in a browser, and the Javadoc seems to be there:

```
getTextDocumentService()
Provides access to the textDocument services.
```

**Comment by svenefftinge** [comment]
We will look into the problems you described. In the meantime could you share the failing tests in a separate issue. They are all successful for me and on the server http://services.typefox.io/open-source/jenkins/job/lsapi/15/testReport/.

**Comment by svenefftinge** [comment]
For the core part we should remove the Xtend source as primary, since the generated Java code is very readable. For the services I'd like to keep the xtend code as primary code.

**Comment by svenefftinge** [comment]
would be solved by doing #28

**Comment by bruno-medeiros** [comment]
Yup, having #28 , a primary Java code base, would be quite cool.

**Comment by svenefftinge** [comment]
Closing this, as we have mostly completed #28 for LSP4j.
