### ISSUE TITLE
LanguageServerToJson sends bad message on startup

### ISSUE THREAD

**Issue by georgewfraser** [TypeFox/ls-api#2]
I set up a minimal example using LanguageServerToJson and a LanguageServer that basically does nothing, and when I run it with VS Code I get this error on startup:

```
Recevied message which is neither a response nor a notification message:
{
"id": "0",
"jsonrpc": "2.0"
}
```

**Comment by spoenemann** [comment]
> I set up a minimal example using LanguageServerToJson and a LanguageServer that basically does nothing

What does _"nothing"_ mean? What do you return on `initialize()`?

**Comment by georgewfraser** [comment]
I return a `new InitializeResult() { ... }` anonymous class that returns falses / nulls from the getter.

It seems that gson doesn't like the anonymous class. Switching to InitializeResultImpl fixes it. I'm not familiar with gson but this seems like a weird trap.

**Comment by svenefftinge** [comment]
Yeah, I fell over it the other day as well.

**Comment by svenefftinge** [comment]
Here's the explanation https://github.com/google/gson/blob/master/UserGuide.md#nested-classes-including-inner-classes

**Comment by spoenemann** [comment]
Gson has quite flexible ways to customize serialization if the default behavior doesn't work for the objects you return. Just create a subclass of `MessageJsonHandler` where you build a custom `Gson` with a `GsonBuilder` in the constructor, and pass that handler to the `LanguageServerToJsonAdapter`.
