### ISSUE TITLE
Get the version of a file after a didChange

### ISSUE THREAD

**Issue by mickaelistria** [TypeFox/ls-api#20]
ATM, it seems like the client of ls-api has to manage the version: the ls-api doesn't provide a way to get the version of the document after a change. Is this a limitation from language server protocol or from the ls-api?
ATM, I can manage versions with static counter, but in case of concurrent edition of the same file (for sure deprecated but still doable), being able to retrieve the version from server seems more reliable.

**Comment by cdietrich** [comment]
you may have a look at https://github.com/Microsoft/language-server-protocol/issues/10

**Comment by svenefftinge** [comment]
As explained in the ticket Christian referenced, it is invalid to send requests to the document in parallel, as the order of incoming change events is important.
