### ISSUE TITLE
Debugging timeouts

### ISSUE THREAD

**Issue by mickaelistria** [TypeFox/ls-api#21]
I'm using the ls-api to connect to a few language server: CSS and JSon one from VSCode extensions, and https://github.com/OmniSharp/omnisharp-node-client/tree/master/languageserver . I connect to those servers using: https://github.com/eclipselabs/eclipse-language-service/blob/master/org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServerWrapper.java#L96 .
Completion is implemented in 

I get some mixed results:
- CSS using VSCode support: completion works, hover freezes (I got in touch with a VSCode developer who told me that at the moment, hover is working without issue for VSCode so that the issue is most likely in my client
- JSon using VSCode support: completion woks, didn't try hover
- CSharp using omnisharp-node-client: completion freezes

So I'd like to debug these timeouts. Is there a way to monitor what gets sent/received by the ls-api? Some option to enable or some breakpoints to set at a particular place?

**Comment by mickaelistria** [comment]
Also, connecting to those servers, I don't manage to receive diagnostics. This could be related.
My impression (didn't monitor the streams yet) is that some messages are received in a different format than the one supported by ls-api, resulting in timeouts or unreceived diagnostics.

**Comment by svenefftinge** [comment]
You can add listeners to the LanguageServerProtocol returned by JsonBasedLangaugeServer#getProtocol for in and out messages as well as errors.
See https://github.com/TypeFox/ls-api/blob/master/io.typefox.lsapi.services/src/main/java/io/typefox/lsapi/services/json/LanguageServerProtocol.xtend#L61

**Comment by mickaelistria** [comment]
Thanks, that was very helpful.
