### ISSUE TITLE
Telemetry notification

### ISSUE THREAD

**Issue by natgabb** [TypeFox/ls-api#22]
Is there a plan to include this in the api?
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#telemetry-notification
It was added to the protocol specification about a month ago.

**Comment by svenefftinge** [comment]
Of course, we will keep up with any enhancements done in the protocol. Thanks for pointing this out.

**Comment by spoenemann** [comment]
Forgot to add the notification to the LanguageServer interface, will do that tomorrow.

**Comment by svenefftinge** [comment]
In order to see what changes we might have missed in future we should maybe reference a commit of the protocol.md (e.g. in the README), so we see how much we lack behind?

**Comment by natgabb** [comment]
Thanks for the quick response :)

**Comment by spoenemann** [comment]
This was introduced in [d2d2bfb](https://github.com/Microsoft/language-server-protocol/commit/d2d2bfb9186f5c3660fb9ceeb0f6fb9dc0a1378f). I haven't seen any other protocol changes after that.
