### ISSUE TITLE
Canno build latest version, `:io.typefox.lsapi:test` test failures

### ISSUE THREAD

**Issue by bruno-medeiros** [TypeFox/ls-api#25]
I was trying to build ls-api locally, but I have test failures for `:io.typefox.lsapi:test`:
[out.txt](https://github.com/TypeFox/ls-api/files/376451/out.txt)
I tried several other recent revisions, but could not build any I tried, they all had test or 
compilation failures.

**Comment by svenefftinge** [comment]
We need to investigate why that is. In the meantime you could use the results of the latest builds:
http://services.typefox.io/open-source/jenkins//job/lsapi/32/artifact/build/

**Comment by bruno-medeiros** [comment]
Maybe another Windows-specific issue? Could be path separator issues this time :sweat_smile:  Here's tests results if it helps:
[test-results.zip](https://github.com/TypeFox/ls-api/files/376650/test-results.zip)

**Comment by svenefftinge** [comment]
likely. Seems like we really need windows users working on this ;-)

**Comment by spoenemann** [comment]
Same kind of line endings problem as in #18.

**Comment by bruno-medeiros** [comment]
Yay, it builds successfully on Windows now. 
(If it was Java code I would have taken a stab at debugging it myself, but being Xtend, I couldn't be bothered :sweat_smile: )
