### ISSUE TITLE
Migrate to Java 8

### ISSUE THREAD

**Issue by svenefftinge** [TypeFox/ls-api#28]
In order to make contributions and usage as simple as possible for Java devs, we should migrate our code base to Java 8. (see comments like https://github.com/TypeFox/ls-api/issues/25#issuecomment-234561406)

For the protocol types we should still use a code generator written in Xtend (just because using Java here would be too painful) but the actual implementation should be pure Java.

Also once there is a formal definition of the protocol (see https://github.com/Microsoft/language-server-protocol/pull/40) we should use that as the source for our code generator.

**Comment by svenefftinge** [comment]
While reworking the code for lsp4j, with the main two goals
1) better separation of jsonrpc and lsp
2) easier custom extendability of LSP
I write all the new code in J8. There are still some left over, which we will translate in the coming days.

**Comment by spoenemann** [comment]
Finished the conversion for the service / jsonrpc code. The protocol data structures are still generated with Xtend. How this is going to be done in the future is discussed in #49.
