### ISSUE TITLE
No solution to resolve package javax.annotations >= 3.0.0 in OSGi

### ISSUE THREAD

**Issue by mickaelistria** [TypeFox/ls-api#29]
I'm migrating to ls-api 0.3.0. However, I'm stuck at having OSGi resolve javax.annotations 3.0.0 (jsr305). All artifacts I found aren't OSGi-able. Do you have an artifact to recmmend for that? cc @iloveeclipse

**Comment by mickaelistria** [comment]
Since according to https://github.com/TypeFox/ls-api/commit/e83d3dde2d5bd5e2bb261779d5bfc3df1f7a0366 , this seems to be plain usage of @Nullable annotation, would it be possible to set dependency on a lower, OSGi-able version such as 1.1.0?

**Comment by nedtwigg** [comment]
Another solution is `javax.annotation;resolution:=optional`.  It's only needed for compile-time checking.

**Comment by spoenemann** [comment]
I'll remove the version constraint from the generated manifest.

**Comment by spoenemann** [comment]
> It's only needed for compile-time checking.

The annotation has runtime retention, and in our case we actually use it to check data structures at runtime.

**Comment by mickaelistria** [comment]
@spoenemann thanks, Please notify as soon as a p2 repo without the version constraint is available.

**Comment by spoenemann** [comment]
Build is done: http://services.typefox.io/open-source/jenkins/job/lsapi/

**Comment by mickaelistria** [comment]
Thanks. However, the version constraint is still set in the io.typefox.lsapi.services bundle.

PS: I didn't find a way to reopen this issue. Do you want me to create a new one?
