### ISSUE TITLE
Wrong version constraint from io.typefox.lsapi.services to javax.annotations 3.0

### ISSUE THREAD

**Issue by mickaelistria** [TypeFox/ls-api#30]
The io.typefox.lsapi.services bundle still specify a version constraint on javax.annotations. However, no bundle export package javax.annotations >= 3.0 (most JSR305 impelementation I've seen have bundle version 3.0 but package version 1.1.0).
This prevents p2 and OSGi to use the ls-api. Please consider removing this version constraint, as it was done for other bundles in #29

**Comment by spoenemann** [comment]
Sorry, I forgot to apply the fix for #29 to lsapi.services, too.

**Comment by mickaelistria** [comment]
Same thing for the io.typefox.lsapi.annoations bundle (sorry I didn't notice it earlier)
