### ISSUE TITLE
Implementations should take interfaces in their setters instead of implementations

### ISSUE THREAD

**Issue by natgabb** [TypeFox/ls-api#34]
Ex:

```
HoverImpl hover = new HoverImpl();
Range range = createSomeRange();
hover.setRange(range);
```

This wouldn't work because `setRange` takes a `RangeImpl`. This makes it very hard to write code that doesn't depend on implementations throughout.

**Comment by natgabb** [comment]
Also, it would be really nice if implementations had non-default constructors so that we could do something like this:

```
Range range = getRange();
List<MarkedString> contents = getContents();
Hover hover = new HoverImpl(content, range);
```

**Comment by JanKoehnlein** [comment]
This seems to be fixed on head:
- We no longer have setters, as the elements should be immutable. 
- Instead, we have a builder API for the elements. That yields also a much more stable API when the protocol is extended.
- I haven't found any reference to impl classes in the API. 

Feel free to reopen if I am wrong.
