### ISSUE TITLE
Break down io.typefox.lsapi.services module

### ISSUE THREAD

**Issue by akosyakov** [TypeFox/ls-api#36]
I would like to break down io.typefox.lsapi.services on the following modules:

| module | responsibility | languages | depends on |
| --- | --- | --- | --- |
| io.typefox.lsapi.services | java interfaces for services defined by the language server protocol | java | io.typefox.lsapi |
| io.typefox.lsapi.transport | base interfaces to organize communication between the client (tool) and server sides like _LanguageEndpoint_, _MessageReader_, _MessageWriter_, _MessageTracer_ and base or typical implementations of them, like _AbstractLanguageEndpoint_, _ConcurrentMessageReader_ and _PrintMessageTracer_ | java, xtend | io.typefox.lsapi |
| io.typefox.lsapi.json | JSON based implementation of _MessageReader_ and _MessageWriter_ | java, xtend | io.typefox.lsapi.transport |
| io.typefox.lsapi.client | the client (tool) side implementation of _LanguageEndpoint_ for communication with the server side | java, xtend | io.typefox.lsapi.transport |
| io.typefox.lsapi.server | the server side implementation of _LanguageEndpoint_ for communication with the client (tool) side | java, xtend | io.typefox.lsapi.transport |

Such structure let users only consume what they need, for example:
- for communication with a _json_ based language server **io.typefox.lsapi.client** and **io.typefox.lsapi.json** are required;
- for communication with a _non-json_ based language server **io.typefox.lsapi.client** is required and custom implementation of **MessageReader** and **MessageWriter** should be provided;
- for communication with a _json_ based client of the language server **io.typefox.lsapi.server** and **io.typefox.lsapi.json** are required; 
- for communication with a _non-json_ based client of the language server **io.typefox.lsapi.server** is required and custom implementation of **MessageReader** and **MessageWriter** should be provided.

**Comment by akosyakov** [comment]
For comparison a decomposition of typescript SDK: https://github.com/Microsoft/vscode-languageserver-node#vscode-language-server---node. It consist of [a base package](https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/main.ts#L111) hiding implementation details of the base jsonrpc protocol, and [client](https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/main.ts#L84) and [server](https://github.com/Microsoft/vscode-languageserver-node/blob/master/server/src/main.ts#L444) wrappers packaged correspondingly.

Notice how all connection interfaces expose generic method for registering handlers and sending requests and notification, so one can easily extend the protocol.

**Comment by spoenemann** [comment]
What do you mean by _modules_? Packages or Jars?

**Comment by akosyakov** [comment]
@spoenemann jars

**Comment by spoenemann** [comment]
I don't see the benefit in such a fine-grained splitting into multiple jars. I would understand separating the JSON dependent part in order to get rid of the Gson dependency in cases where you want to implement you own message passing, but otherwise it shouldn't matter to have a few kilobytes more code than you actually need?

**Comment by akosyakov** [comment]
@spoenemann I don't care about a size either, but rather about clear structure and API. if one implement a server he should not bother with client side interfaces and classes, the same for the client side.

**Comment by spoenemann** [comment]
Ok, we should discuss this when we review the API after the code transfer to Eclipse.

**Comment by akosyakov** [comment]
https://github.com/Microsoft/language-server-protocol/issues/86#issuecomment-252194346 - arguments to decouple the LS protocol from the transport level and the transport from json based implementation

**Comment by akosyakov** [comment]
Also think we should have `io.typefox.lsapi.shared` that have common useful service on the LS protocol level, e.g. FileWatchingLanguageServer can watch file changes and be applied on the client and server sides.

**Comment by svenefftinge** [comment]
For lsp4j I splitted it up in two separate modules
- org.eclipse.lsp4j.jsonrpc (just the jsonrpc implementation, without any knowledge of LSP)
- org.eclipse.lsp4j (the LSP definitions using jsonrpc)

I think this is a reasonable splitting, I don't see how anyone would want to use jsonrpc without json, but even that would be possible now. It is just that the json specific stuff is not in its own module (but package).

For the client / server separation, on jsonrpc level there is no distinction as both are just endpoints. On LSP level it makes sense to have the interfaces in one module, as a language server usually gets parameterized with a language client to communicate back (and vice versa).
