### ISSUE TITLE
PublishDiagnosticsParamsBuilder takes a single Diagnostic instead of a List<Diagnostic>

### ISSUE THREAD

**Issue by natgabb** [TypeFox/ls-api#37]

**Comment by natgabb** [comment]
I see now that `PublishDiagnosticsParamsBuilder#diagnostic` adds a diagnostic to a list instead of setting a single diagnostic. It seems weird to me that there is no distinction between the two. Maybe the name should be `addDiagnostic`?

**Comment by akosyakov** [comment]
I think it is a valid point, addDiagnostic is less confusing, also for other interfaces which make use of collections.

**Comment by akosyakov** [comment]
It also would be nice to have addDiagnostics method.

**Comment by natgabb** [comment]
Another reason a method that takes a List<Diagnostic> should be added: It is currently not possible to use the builder to create a `PublishDiagnosticsParams` with an empty list of diagnostics. Instead the parameter is set to null. Probably not too useful for `PublishDiagnosticsParams` specifically but this is the case for all interfaces with Lists.

**Comment by akosyakov** [comment]
@natgabb how addDiagnostics will help you? in you case you will need something like setDiagnostics to set an empty list

**Comment by natgabb** [comment]
@akosyakov that's true! I think that all the builders for interfaces with lists should have: `setDiagnostics(List<Diagnostic> l)` or simply `diagnostics(List<Diagnostic> l)` (to follow the pattern of all the other builders) as well as a `addDiagnostic(Diagnostic d)`, and optionally `addDiagnostics(List<Diagnostic> l)`. This way you can create an instance with an empty list instead of a null reference.

**Comment by akosyakov** [comment]
@JanKoehnlein what do you think about this one?

**Comment by svenefftinge** [comment]
Not having builders at all would help avoiding such confusion.

**Comment by svenefftinge** [comment]
We removed support for builders in lsp4j
