### ISSUE TITLE
A method to know whether connection to language server is still active

### ISSUE THREAD

**Issue by mickaelistria** [TypeFox/ls-api#44]
On LanguageClientEndpoint, it would be useful to get a method to know whether the connection is still working, ie if the reader/writer are still active, ie in case of StreamMessageReader, the value of `keepRunning`.

**Comment by akosyakov** [comment]
@mickaelistria If you use ConcurrentMessageReader, you can check reader by calling  ConcurrentMessageReader.isRunning

**Comment by mickaelistria** [comment]
I have a language server using ConcurrentMessageReader that seems running wll (I receive diagnostics), but using `((ConcurrentMessageReader)this.languageClient.getReader()).isRunning()` seems to often return `false`, although all streams are still alive. I would expect this to return `true` unless there is an IO issue.

**Comment by mickaelistria** [comment]
This could be caused by issue #43 : if there is a parsing error in the response, `isRunning()` returns false, although the stream is still working.

**Comment by mickaelistria** [comment]
I have the impression that the `isRunning()` is the right method and does what desired, but issue #43 makes it return erroneous results.
Then I'm closing this one as I believe fixing #43 would make `isRunning()` reliable for the desired use case.
