### ISSUE TITLE
Commit generated java code for io.typefox.lsapi

### ISSUE THREAD

**Issue by akosyakov** [TypeFox/ls-api#45]
It should be possible to read source code for derived impls and builders classes from github.

**Comment by svenefftinge** [comment]
no longer valid due to #28

**Comment by spoenemann** [comment]
@akosyakov referred to the data structures, which are discussed in #49, and not the jsonrpc code, which was translated in #28.

**Comment by spoenemann** [comment]
Now done in eclipse/lsp4j#2
