### ISSUE TITLE
InvalidMessageException is silently ignored even though MessageTracer is present

### ISSUE THREAD

**Issue by georgewfraser** [TypeFox/ls-api#46]
Message:

io.typefox.lsapi.services.transport.InvalidMessageException: Error: The property 'supportedLanguages' must have a non-null value.
The message was:
    ResponseMessageImpl [
      id = "0"
      result = InitializeResultImpl [
        capabilities = ServerCapabilitiesImpl [
          textDocumentSync = Incremental
          hoverProvider = true
          completionProvider = CompletionOptionsImpl [
            resolveProvider = null
            triggerCharacters = null
          ]
          signatureHelpProvider = null
          definitionProvider = true
          referencesProvider = true
          documentHighlightProvider = null
          documentSymbolProvider = true
          workspaceSymbolProvider = true
          codeActionProvider = null
          codeLensProvider = null
          documentFormattingProvider = null
          documentRangeFormattingProvider = null
          documentOnTypeFormattingProvider = null
          renameProvider = null
        ]
        supportedLanguages = null
      ]
      error = null
      jsonrpc = "2.0"
    ]

Stack trace:

0 = {StackTraceElement@1812} "io.typefox.lsapi.services.json.MessageJsonHandler.serialize(MessageJsonHandler.xtend:258)"
1 = {StackTraceElement@1813} "io.typefox.lsapi.services.json.MessageJsonHandler.serialize(MessageJsonHandler.xtend:250)"
2 = {StackTraceElement@1814} "io.typefox.lsapi.services.json.StreamMessageWriter.write(StreamMessageWriter.xtend:37)"
3 = {StackTraceElement@1815} "io.typefox.lsapi.services.transport.AbstractLanguageEndpoint.sendMessage(LanguageEndpoint.xtend:93)"
4 = {StackTraceElement@1816} "io.typefox.lsapi.services.transport.AbstractLanguageEndpoint.sendResponse(LanguageEndpoint.xtend:115)"
5 = {StackTraceElement@1817} "io.typefox.lsapi.services.transport.server.LanguageServerEndpoint.lambda$_doAccept$7(LanguageServerEndpoint.xtend:181)"
6 = {StackTraceElement@1818} "java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)"
7 = {StackTraceElement@1819} "java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)"
8 = {StackTraceElement@1820} "java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140)"
9 = {StackTraceElement@1821} "io.typefox.lsapi.services.transport.server.LanguageServerEndpoint._doAccept(LanguageServerEndpoint.xtend:175)"
10 = {StackTraceElement@1822} "io.typefox.lsapi.services.transport.server.LanguageServerEndpoint.doAccept(LanguageServerEndpoint.xtend:117)"
11 = {StackTraceElement@1823} "io.typefox.lsapi.services.transport.server.LanguageServerEndpoint.accept(LanguageServerEndpoint.xtend:114)"
12 = {StackTraceElement@1824} "io.typefox.lsapi.services.transport.server.LanguageServerEndpoint.accept(LanguageServerEndpoint.xtend)"
13 = {StackTraceElement@1825} "io.typefox.lsapi.services.transport.AbstractLanguageEndpoint.handleMessage(LanguageEndpoint.xtend:67)"
14 = {StackTraceElement@1826} "io.typefox.lsapi.services.transport.AbstractLanguageEndpoint.lambda$connect$4(LanguageEndpoint.xtend:61)"
15 = {StackTraceElement@1827} "io.typefox.lsapi.services.json.StreamMessageReader$1.apply(StreamMessageReader.java:45)"
16 = {StackTraceElement@1828} "io.typefox.lsapi.services.json.StreamMessageReader$1.apply(StreamMessageReader.java:43)"
17 = {StackTraceElement@1829} "io.typefox.lsapi.services.json.StreamMessageReader.handleMessage(StreamMessageReader.xtend:128)"
18 = {StackTraceElement@1830} "io.typefox.lsapi.services.json.StreamMessageReader.listen(StreamMessageReader.xtend:61)"
19 = {StackTraceElement@1831} "io.typefox.lsapi.services.transport.AbstractLanguageEndpoint.connect(LanguageEndpoint.xtend:60)"
20 = {StackTraceElement@1832} "org.javacs.Main.run(Main.java:148)"
21 = {StackTraceElement@1833} "org.javacs.Main.main(Main.java:69)"

**Comment by svenefftinge** [comment]
I have removed the property 'supportedLanguages'. Can this issue be closed or could you clarify what this is about?

**Comment by georgewfraser** [comment]
The problem is that ls-api crashes - it stops responding to messages - without logging an error!

**Comment by svenefftinge** [comment]
We need to check how lsp4j behaves here.

**Comment by svenefftinge** [comment]
We've moved everything to https://github.com/eclipse/LSP4J. 
Please file it there again if it is still an issue.
