### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by mickaelistria** [TypeFox/ls-api#52]
As this project is using Gradle and Xtend, it's a bit trickier to configure that the usual.
Specifically, I don't manage to get BuildShip to generate a right classpath, even if I do `right-click > Gradle > refresh Gradle project` many times on any module.
A contribution guide would be welcome.

**Comment by svenefftinge** [comment]
You should use buildship 2.0 http://download.eclipse.org/buildship/updates/e45/milestones/2.x/

**Comment by spoenemann** [comment]
Yes, we'll add a contribution guide to [lsp4j](https://projects.eclipse.org/projects/technology.lsp4j) as soon as it has been kicked off.

**Comment by svenefftinge** [comment]
Added  https://github.com/TypeFox/ls-api/blob/lsp4j/Contributing.md
