### ISSUE TITLE
0.3.0-SNAPSHOT is gone from oss.sonatype.org

### ISSUE THREAD

**Issue by jiahuijiang** [TypeFox/ls-api#60]
https://oss.sonatype.org/content/repositories/snapshots/io/typefox/lsapi/io.typefox.lsapi/0.3.0-SNAPSHOT/ is returning 404 right now
are the snapshots still being published anywhere?

**Comment by dhuebner** [comment]
No, we released 0.3.0.

**Comment by spoenemann** [comment]
https://oss.sonatype.org/service/local/repositories/releases/content/io/typefox/lsapi/io.typefox.lsapi/0.3.0/

**Comment by dhuebner** [comment]
@spoenemann I have even a better one :)

http://repo1.maven.org/maven2/io/typefox/lsapi/io.typefox.lsapi.services/0.3.0/
