### ISSUE TITLE
Request initialize failed with message: Cannot read property 'languageIds' of undefined

### ISSUE THREAD

**Issue by mickaelistria** [TypeFox/ls-api#63]
Same as issue #47 , but with a recent version of LSP4J, testing VSCode-json server.
As a result the capabilities returned by server are null or not usable, so one cannot access the completion trigger characters for example.

**Comment by kaloyan-raev** [comment]
@mickaelistria check if this PR to VSCode resolves the issue for you: https://github.com/Microsoft/vscode/pull/12259

**Comment by mickaelistria** [comment]
@kaloyan-raev Maybe VSCode has a part of the issue, but I think LSP4J should handle this properly. It used to work better in previous extensions.

**Comment by svenefftinge** [comment]
It's not clear to me what should be done here. 
If you feel there is something we should do for lsp4j in this context, please reopen.

**Comment by mickaelistria** [comment]
I cannot reopen, but

> As a result the capabilities returned by server are null or not usable,

I would rather retrieve the capabilities anyway.

**Comment by svenefftinge** [comment]
I think there should be an exception, because there was a parsing error in the message.

**Comment by mickaelistria** [comment]
I'll have to check again, but in this case, IIRC, this minor and forgivable parsing error prevents from retrieved ServerCapabilities as a whole. In that case of an unexpected property in the object, a more merciful implementation would be to log the error, but to keep on parsing the object and to return the ServerCapabilities anyway.
