### ISSUE TITLE
There are still Versions of LSApi with the typo is ws service floating around

### ISSUE THREAD

**Issue by cdietrich** [TypeFox/ls-api#65]
if i do a fresh checkout of xtext with oomph gradle graps a version of ls services with the typo in the ws service didChangeConfiguraton

**Comment by cdietrich** [comment]
maybe from here https://oss.sonatype.org/content/repositories/snapshots/io/typefox/lsapi/io.typefox.lsapi.services/0.4.0-SNAPSHOT/

**Comment by spoenemann** [comment]
Should be better now.
