### ISSUE TITLE
Add additional GPL-compatible license

### ISSUE THREAD

**Issue by svenefftinge** [TypeFox/ls-api#9]
As EPL is not compatible with GPL, we should have an alternative license to be used.
MIT seems to be a good choice (similar to EPL but GPL-compatible).

**Comment by svenefftinge** [comment]
See https://github.com/ensime/ensime-server/issues/1498#issuecomment-223749309

**Comment by svenefftinge** [comment]
ls-api is going to move over to Eclipse and be distributed under two licenses. EPL and EDL (a BSD 3-clause license).
See https://projects.eclipse.org/proposals/lsp4j

**Comment by fommil** [comment]
I recommend Apache 2.0 instead of BSD or MIT style licenses. http://fommil.github.io/scalasphere16/

**Comment by spoenemann** [comment]
EDL has already been approved as additional license: https://projects.eclipse.org/projects/technology.lsp4j
So I consider this fixed.
